version: '3.7'

services:
  decidim:
    image: decidim-br-app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis-queue
      - redis-cache

  postgres:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  redis-queue:
    image: redis:6.0.12-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.0.12-alpine
    ports:
      - 6380:6379
    volumes:
      - redis-cache-data:/data
  
  migrate:
    image: decidim-br-app
    command: sh -c "rails db:create db:migrate"
    depends_on:
      - postgres
      - decidim

  mailcatcher:
    image: decidim-br-app
    ports:
      - 1080:1080
      - 1025:1025
    command: sh -c "mailcatcher --foreground --ip=0.0.0.0"
    depends_on:
      - decidim

  sidekiq:
    image: decidim-br-app
    command: sh -c "bundle exec sidekiq"
    depends_on:
      - redis-queue
      - decidim

volumes:
  redis-queue-data:
  redis-cache-data:
  postgres-data:
