name: RuboCop Linter
on: [push, pull_request]
jobs:
  lint:
    name: RuboCop Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.x  # Substitua pela versão do Ruby usada no seu projeto

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RuboCop
        run: bundle exec rubocop
