name: Ruby Tests
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RSpec (replace with your testing command)
        run: bundle exec rspec
